version: "3"

services:

  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - mysql
      - php
    container_name: docker_nginx3

  php:
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    container_name: docker_php3
  node:
      build:
          context: .
          dockerfile: docker/nodejs/DockerFile
      tty: true
      ports:
          - "5173:5173"
      working_dir: /var/www
      volumes:
          - .:/var/www
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/mysql/volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9090:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
  composer:
    build:
      dockerfile: docker/composer/Dockerfile
    volumes:
      - db_data:/var/www/html

  artisan:
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]

volumes:
  db_data:
networks:
    app-network:
        driver: bridge
